### ISSUE TITLE
pkg_resources Module not foun, py3.12

### ISSUE THREAD

**Issue by EBGlom** [dnvgl/qats#131]
**Describe the bug**
qats application fails to start as pgk_resources module is not found
NB: this is on an old repo with potentially some historical files here and there, but the poetry env is brand new (py 3.12.4)

**To Reproduce**
write qats app in terminal (see screenshot)

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/ba6a2890-ea17-4b26-a6d0-71333ed890d2)

**Desktop (please complete the following information):**
 - OS: W 10

**Additional context**
Will seek some work-arounds and report back

**Comment by tovop** [comment]
Hi! No time today but I'll have a look at it soon. Keep me posted.

**Comment by tovop** [comment]
I believe there is generally a problem with pkg_resources on 3.12. I think @eneelo has encountered this some time ago.

**Comment by eneelo** [comment]
As I recall, we removed dependencies to ``pkg_resources`` related to getting version info, but two other imports/usages remain:
![image](https://github.com/user-attachments/assets/1fdf92fc-d821-42a1-87e1-af7820d3767d)

This issue seems to be addressed in https://github.com/mu-editor/mu/issues/2485, and documentation on how to migrate to ``importlib_resources`` is provided in https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename. Looks like an easy fix, unless there is some twist I don't see immediately.

**Comment by EBGlom** [comment]
Seeming functioning work-around in py 3.12:

cli.py:
![image](https://github.com/user-attachments/assets/0aaff062-1d9b-403c-8f21-229415ceed1a)


gui.py:
![image](https://github.com/user-attachments/assets/3234b000-f797-4b7e-8a2f-a3a98011a182)
and
![image](https://github.com/user-attachments/assets/93435e6f-80cb-4574-9dfd-68158f259b9a)

QIcon is not fond of pathlib type arguments

**Comment by eneelo** [comment]
That's good! I didn't see your last post before establishing a new branch and PR to test this solution. See https://github.com/dnvgl/qats/pull/132

**Comment by EBGlom** [comment]
Didn't expect this speedy turn-around here :)

I had to use importlib.resources (py 3.12 only).
![image](https://github.com/user-attachments/assets/10f8c489-80dd-4bb2-b086-879ca31b57f5)

I pushed a minor update which catches the ImportError

**Comment by tovop** [comment]
Lovely! Quickly solved @eneelo and @EBGlom
