### ISSUE TITLE
Menu items

### ISSUE THREAD

**Issue by tovop** [dnvgl/qats#15]
Status on creating menu items (start menu and desktop links):
* The implementation of menuinst with conda seems to be broken and not very well supported nor documented
* Menu items can be created/removed on installation/uninstallation with conda using post-link/pre-unlink script. However this require building the package on windows agents (which are not available open source/free)
* Menu items can be created with setuptools by creating a custom install command-handle. However this is not compatible with wheels (it seems). There are also certain other challenges.
* setuptools and conda advise to avoid post-link/post-install scripts
* Newer/better pure-python package managers e.g. Poetry does not allow custom executables/scripts to run on install/uninstall time.

I suggest to create CLI entry points for the user to create start menu and desktop links e.g.

```
qats config --create-links
```
... and

```
qats config --remove-links
```

That way we can build QATS for Windows (with menu items) and for Linux using a Linux build agent. We do not violate the best practices for package building. And we can distribute the package both as tarball, wheel and conda packages.

**Comment by tovop** [comment]
@eneelo I would like you thoughts on this one.

Supporting argument. I think it is good to also provide tarballs and wheels, as most python projects do. The reason is that many use cases rely on the pure Python package managers Pip, Poetry, Packagr etc.

**Comment by eneelo** [comment]
@tovop: I support the suggested solution with CLI entry points. I also strongly support your comments about avoiding dirty fixes (such as post-link/post-install scripts) and to provide distribution of tarballs and wheels through e.g. Pip/PyPI, Poetry, etc.

Not sure how relevant it is, but I'd like to add one comment; being forced to build on Linux, we should investigate possibilities to make the GUI entry point [on windows] run using pythonw.exe instead of python.exe, to avoid the slightly annoying cmd window that opens along with the GUI. From what I remember, this is an issue at least for console script entry points, when conda builds are converted from Linux to Windows. Any thoughts or newer experience on this topic?

**Comment by tovop** [comment]
The CLI commands to create start menu and desktop links and remove them are renamed for clarity, see 785811141de49efce3d49f7533a49f16435d5a06.

```
qats config --link-app
```
... and

```
qats config --unlink-app
```
