### ISSUE TITLE
Label changer in time series, power spectrum and min/max not working

### ISSUE THREAD

**Issue by mjohannesen** [dnvgl/qats#48]
Changing the of a variable in the label field does not change the name of the actual variable in the plot. 

When clicking display again the label is reset to the original value.

**Comment by eneelo** [comment]
Please elaborate on the issue described. Are you referring to the native matplotlib-button ("edit axis, curve (...)"? If so, make sure to activate "(Re-)Generate automatic legend" on the Axes tab of the figure options window that opens. See screeshots below.

The reason why the values are reset when clicking Display is that this causes a re-generation of the plot. In order to keep the values, we need to change the way labels are set/changed. Not impossible, but requires code development.
 
![image](https://user-images.githubusercontent.com/45939678/65586827-19eb3480-df85-11e9-839b-3fa8bf44d858.png)

![image](https://user-images.githubusercontent.com/45939678/65588379-b6aed180-df87-11e9-9ffe-8801523a0a32.png)

**Comment by mjohannesen** [comment]
Thank you for the quick reply. I did not know that was an option. It feels a bit counter-intuitive to activate that option, as you are likely to want your changes to happen when you make them? 

I don't think it is an important feature to keep the values when clicking display, it was more to give some background info about what i thought was the issue.

**Comment by eneelo** [comment]
> Thank you for the quick reply. I did not know that was an option. It feels a bit counter-intuitive to activate that option, as you are likely to want your changes to happen when you make them?
> 
> I don't think it is an important feature to keep the values when clicking display, it was more to give some background info about what i thought was the issue.

I agree about the lack of intuitiveness. Unfortunately, this is the price of only offering the native matplotlib way of updating labels interactively. The primary objective of the GUI is quick access to time series (+ spectra, etc.) inspection, so in general we recommend using the underlying qats library in scripts when custom figures are needed. However; if a request (issue) is filed, we will consider the possibility to improve this functionality (should we find time to do it some time in the future...).
