### ISSUE TITLE
TsDB.register.keys for witurb.bin

### ISSUE THREAD

**Issue by erikbyholthanssen** [dnvgl/qats#97]
Hi

Applying TsDB.fromfile( *witurb.bin).register returns odict. 
Odict.keys() include wind turbine name only.

I'd like the keys to include contents abbrivated as per key .txt-file. 

Regards, Erik

**Comment by eneelo** [comment]
Hi,
Please provide an example of what you get vs. what you would like to have, and preferably also a screenshot of associated line(s) in key-file.

BR, Erling

**Comment by erikbyholthanssen** [comment]
Hi. 

What I get on e.g. elmfor.bin or results.tda is shown on the left figure. Every timeseries has a unique ID including parsing of data/description. 

For the witurb.bin file only the name of the wind turbine is returned (right figure) for all elements of the TsDB. 
I would like the timeseries names to include contents abbrivated, e.g. 'RotorSpeed'.

Thanks for your .list() tip.

Regards, Erik

![witurb](https://user-images.githubusercontent.com/98746069/208674781-fd90cec7-8fe8-41e1-acbc-51f0b67b66bc.JPG)

**Comment by eneelo** [comment]
Thanks for the details. It seems that the format of the key-file (`key_<>_witurb.txt`) has changed. Or, perhaps, depends on whether the model includes one or more turbines? Any idea?

When the support for `<>_witurb.bin` files was added, it was based on an example key-file that looked like this:
![image](https://user-images.githubusercontent.com/45939678/208677376-f1d0a3f1-20e2-4a13-9903-ef3c1b7f3c7b.png)

... whereas your key-file includes an additional column with the turbine name (which is then interpreted by `qats` as the time series name).

Since the columns are space-delimited (not tab, unfortunately), we need to think through how we interpret the file and work out whether turbine name is given or not. I have no immediate and robust solution for that, but suggestions are welcome.

In the meantime, the best quickfix on your side would probably be to modify the key-file before loading it by `qats.TsDB()`, e.g., by replacing the whitespace after turbine name with an underscore (and replace '-' by whitespace for first two rows with FORTRAN and Time).

**Comment by erikbyholthanssen** [comment]
Thanks,
The model includes one turbine only.
I will consider your quickfix.
Regards Erik
